#!/usr/bin/env python3

import sys

from error_handling.usage import usage
from error_handling.error_handler import error_handler

from methods.bisection import bisection
from methods.newton import newton
from methods.secant import secant

def table_lookup(shape_arg) :
    table = ["1", "2", "3"]

    for i in range(0, 3) :
        if shape_arg == table[i] :
            return i
    error_handler()

def check_args(argv) :
    try :
        for i in range(1, 8) :
            int(argv[i])
    except :
        return False
    return True

ac = len(sys.argv)

if ac == 2 and sys.argv[1] == "-h" :
    usage()
    sys.exit(0)
if ac != 8 :
    error_handler()
if check_args(sys.argv) == False :
    error_handler()
index = table_lookup(sys.argv[1])
func_array = [bisection, newton, secant]
func_array[index]([int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]), int(sys.argv[5])], int(sys.argv[6]))
sys.exit(0)