#! /bin/python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 105torus_2019
## File description:
## 105torus
##

import sys

from error_handling.usage import usage
from error_handling.error_handler import error_handler

from methods.bisection import bisection
from methods.newton import newton
from methods.secant import secant

FUNC_ARRAY = {
    "1": bisection,
    "2": newton,
    "3": secant
}

def check_args(argv) :
    try :
        for i in range(1, 8) :
            argv[i] = int(argv[i])
    except :
        return False
    return True

def main(ac, av):
    if ac == 2 and sys.argv[1] == "-h" :
        usage()
        sys.exit(0)
    if ac != 8 :
        error_handler()
    if check_args(av) is False :
        error_handler()
    if av[1] not in FUNC_ARRAY:
        error_handler()
    FUNC_ARRAY[av[1]]([av[2], av[3], av[4], av[5]], av[6])
    return (0)

if __name__ == "__main__":
    sys.exit(main(len(sys.argv), sys.argv))